// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Cedric Kienzler",
            "url": "cedi.dev",
            "email": "urlshortener@cedi.dev"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/{shortlink}": {
            "get": {
                "description": "redirect to target as per configuration of the shortlink",
                "produces": [
                    "text/html"
                ],
                "tags": [
                    "default"
                ],
                "summary": "redirect to target",
                "parameters": [
                    {
                        "type": "string",
                        "description": "shortlink id",
                        "name": "shortlink",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Success",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "300": {
                        "description": "MultipleChoices",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "301": {
                        "description": "MovedPermanently",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "302": {
                        "description": "Found",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "303": {
                        "description": "SeeOther",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "304": {
                        "description": "NotModified",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "305": {
                        "description": "UseProxy",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "307": {
                        "description": "TemporaryRedirect",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "308": {
                        "description": "PermanentRedirect",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "404": {
                        "description": "NotFound",
                        "schema": {
                            "type": "integer"
                        }
                    },
                    "500": {
                        "description": "InternalServerError",
                        "schema": {
                            "type": "integer"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "URL Shortener",
	Description:      "A url shortener, written in Go running on Kubernetes",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
